# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import node_pb2 as node__pb2


class NodeStub(object):
    """The Node service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AnnouncePeer = channel.unary_unary(
                '/node.Node/AnnouncePeer',
                request_serializer=node__pb2.AnnouncePeerRequest.SerializeToString,
                response_deserializer=node__pb2.AnnouncePeerResponse.FromString,
                )


class NodeServicer(object):
    """The Node service definition.
    """

    def AnnouncePeer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NodeServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AnnouncePeer': grpc.unary_unary_rpc_method_handler(
                    servicer.AnnouncePeer,
                    request_deserializer=node__pb2.AnnouncePeerRequest.FromString,
                    response_serializer=node__pb2.AnnouncePeerResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'node.Node', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Node(object):
    """The Node service definition.
    """

    @staticmethod
    def AnnouncePeer(request, 
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/node.Node/AnnouncePeer',
            node__pb2.AnnouncePeerRequest.SerializeToString,
            node__pb2.AnnouncePeerResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
