
# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: node.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nnode.proto\x12\x04node\"#\n\x13AnnouncePeerRequest\x12\x0c\n\x04peer\x18\x01 \x01(\t"8\n\x14AnnouncePeerResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x0f\n\x07peers\x18\x02 \x03(\t2U\n\x04Node\x12M\n\x0cAnnouncePeer\x12\x19.node.AnnouncePeerRequest\x1a\x1a.node.AnnouncePeerResponse"\x00\x62\x06proto3')



_ANNOUNCEPEERREQUEST = DESCRIPTOR.message_types_by_name['AnnouncePeerRequest']
_ANNOUNCEPEERRESPONSE = DESCRIPTOR.message_types_by_name['AnnouncePeerResponse']
AnnouncePeerRequest = _reflection.GeneratedProtocolMessageType('AnnouncePeerRequest', (_message.Message,), {
  'DESCRIPTOR' : _ANNOUNCEPEERREQUEST,
  '__module__' : 'node_pb2'
  # @@protoc_insertion_point(class_scope:node.AnnouncePeerRequest)
  })
_sym_db.RegisterMessage(AnnouncePeerRequest)

AnnouncePeerResponse = _reflection.GeneratedProtocolMessageType('AnnouncePeerResponse', (_message.Message,), {
  'DESCRIPTOR' : _ANNOUNCEPEERRESPONSE,
  '__module__' : 'node_pb2'
  # @@protoc_insertion_point(class_scope:node.AnnouncePeerResponse)
  })
_sym_db.RegisterMessage(AnnouncePeerResponse)

_NODE = DESCRIPTOR.services_by_name['Node']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ANNOUNCEPEERREQUEST._serialized_start=20
  _ANNOUNCEPEERREQUEST._serialized_end=55
  _ANNOUNCEPEERRESPONSE._serialized_start=57
  _ANNOUNCEPEERRESPONSE._serialized_end=113
  _NODE._serialized_start=115
  _NODE._serialized_end=200
# @@protoc_insertion_point(module_scope)
